
name: Auto Build/Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u sarmirim --password-stdin
          docker build . --tag ghcr.io/sarmirim/gofukurokuju:latest
          docker push ghcr.io/sarmirim/gofukurokuju:latest
